// Package example demonstrates a complete package structure in Clean Architecture.
//
// This package is the canonical reference for teams using portsmith.
// Each file owns exactly one layer. Dependencies point inward only:
//
//	Handler → ServicePort ← Service → RepositoryPort ← Repository
//
// Files ordered from the core outward:
//
//	domain.go      — domain types (core, zero dependencies)
//	errors.go      — domain errors
//	ports.go       — port interfaces (normally generated by portsmith gen)
//	service.go     — business logic
//	repository.go  — storage adapter
//	handler.go     — HTTP adapter
//	dto.go         — request/response structs
//	mappers.go     — domain ↔ DTO conversion
package example

import "time"

// User is the central domain entity of this package.
//
// Rule: domain.go must not import database/sql, net/http, or gorm.
// These are plain Go types. They are safe to pass between all layers.
//
// GORM tags (`gorm:"..."`) are a pragmatic compromise that enables AutoMigrate.
// In a strict Clean Architecture the DB model would live in repository.go as a
// separate struct. For most projects the tags on the domain type are sufficient;
// split only when the DB schema diverges meaningfully from the domain.
type User struct {
	ID        uint     `gorm:"primaryKey"`
	Email     string   `gorm:"uniqueIndex;not null"`
	Name      string   `gorm:"not null"`
	Role      UserRole `gorm:"default:'user'"`
	Active    bool     `gorm:"default:true"`
	CreatedAt time.Time
	UpdatedAt time.Time
}

// UserRole is a role enum. It is defined in the domain, not in the database.
type UserRole string

const (
	RoleUser  UserRole = "user"
	RoleAdmin UserRole = "admin"
)

// CreateParams carries the inputs needed to create a new user.
// The handler converts a DTO → CreateParams; the service receives CreateParams.
//
// Why not pass the DTO directly into the service?
// The service must not know about HTTP-specific concerns (json tags,
// validator tags). CreateParams is the pure "language" of the business operation.
type CreateParams struct {
	Email string
	Name  string
	Role  UserRole
}

// UpdateParams carries the inputs for a partial update.
// Pointer fields mean "field was provided" vs "field was omitted" (partial update).
type UpdateParams struct {
	Name   *string
	Role   *UserRole
	Active *bool
}

// ListFilter holds optional filtering criteria for list queries.
type ListFilter struct {
	Role   *UserRole
	Active *bool
}
