package example

// ports.go — port interfaces for this package.
//
// In a real project this file is generated by:
//
//	portsmith gen ./internal/example
//
// Ports are defined in the package that USES them, not in the package that
// implements them. This is the Dependency Inversion Principle in action.
//
// Handler uses UserService  → UserService is defined here.
// Service uses UserRepository → UserRepository is defined here.
//
// Important: interfaces contain ONLY the methods that are actually called.
// There is no need to copy the entire Repository API into the interface —
// only what is used. This follows the Interface Segregation Principle and
// the Go idiom of small, focused interfaces.

import (
	"context"

	"github.com/miilkaa/portsmith/pkg/pagination"
)

// UserRepository is the storage port used by the service.
//
// Service depends on this interface, not on the concrete *Repository.
// This allows unit-testing the service without a database — a mock is enough.
//
// Compile-time guard: var _ UserRepository = (*Repository)(nil)
// If Repository does not satisfy the interface, the error is a compile error,
// not a runtime panic.
type UserRepository interface {
	Create(ctx context.Context, user *User) error
	FindByID(ctx context.Context, id uint) (*User, error)
	FindByEmail(ctx context.Context, email string) (*User, error)
	Update(ctx context.Context, user *User) error
	Delete(ctx context.Context, id uint) error
	List(ctx context.Context, filter ListFilter, page pagination.OffsetPage) ([]*User, int64, error)
}

// UserService is the business-logic port used by the handler.
//
// Handler depends on this interface, not on the concrete *Service.
// Enables handler unit tests without a service or a database.
type UserService interface {
	Create(ctx context.Context, params CreateParams) (*User, error)
	GetByID(ctx context.Context, id uint) (*User, error)
	Update(ctx context.Context, id uint, params UpdateParams, callerID uint) (*User, error)
	Delete(ctx context.Context, id uint) error
	List(ctx context.Context, filter ListFilter, page pagination.OffsetPage) ([]*User, int64, error)
}

// Compile-time assertions — guarantee that the concrete types satisfy their ports.
// A "does not implement" error here surfaces immediately, not at runtime.
var (
	_ UserRepository = (*Repository)(nil)
	_ UserService    = (*Service)(nil)
)
