package example

// service.go — business logic layer.
//
// Rules for this layer:
//  1. Accepts dependencies ONLY through interfaces (UserRepository).
//  2. Must not know about SQL, gorm, or database/sql.
//  3. Must not know about HTTP, net/http, or gin.
//  4. Contains business rules: validation, authorisation, orchestration.
//  5. Returns domain errors (errors.go), never gorm.ErrRecordNotFound.
//
// How to test:
//   - Inject a mock repository (generated by portsmith mock).
//   - No database required.
//   - Tests live in service_test.go.

import (
	"context"
	"errors"

	"github.com/miilkaa/portsmith/pkg/pagination"
)

// Service implements the business logic for user management.
type Service struct {
	// repo is injected through the interface, not as a concrete *Repository.
	// The field name "repo" follows the portsmith gen convention:
	// the tool looks for s.repo.Method() calls to build the port interface.
	repo UserRepository
}

// NewService creates a new Service. It accepts an interface — easy to test.
func NewService(repo UserRepository) *Service {
	return &Service{repo: repo}
}

// Create creates a new user.
//
// Business rules:
//   - Email must be unique (verified through the repository).
//   - If no role is provided, RoleUser is assigned by default.
func (s *Service) Create(ctx context.Context, params CreateParams) (*User, error) {
	// Check email uniqueness — a business rule, not a SQL constraint.
	existing, err := s.repo.FindByEmail(ctx, params.Email)
	if err != nil && !errors.Is(err, ErrUserNotFound) {
		return nil, err
	}
	if existing != nil {
		return nil, ErrEmailTaken
	}

	role := params.Role
	if role == "" {
		role = RoleUser
	}

	user := &User{
		Email: params.Email,
		Name:  params.Name,
		Role:  role,
	}

	if err := s.repo.Create(ctx, user); err != nil {
		return nil, err
	}
	return user, nil
}

// GetByID returns a user by primary key.
func (s *Service) GetByID(ctx context.Context, id uint) (*User, error) {
	return s.repo.FindByID(ctx, id)
}

// Update modifies user fields.
//
// Business rules:
//   - A regular user cannot change their own role.
//   - A user cannot deactivate themselves (callerID == id && Active = false).
func (s *Service) Update(ctx context.Context, id uint, params UpdateParams, callerID uint) (*User, error) {
	user, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}

	if params.Active != nil && !*params.Active && callerID == id {
		return nil, ErrCannotDeactivateSelf
	}

	if params.Name != nil {
		user.Name = *params.Name
	}
	if params.Role != nil {
		user.Role = *params.Role
	}
	if params.Active != nil {
		user.Active = *params.Active
	}

	if err := s.repo.Update(ctx, user); err != nil {
		return nil, err
	}
	return user, nil
}

// Delete removes a user by ID.
func (s *Service) Delete(ctx context.Context, id uint) error {
	// Verify the user exists before attempting deletion.
	if _, err := s.repo.FindByID(ctx, id); err != nil {
		return err
	}
	return s.repo.Delete(ctx, id)
}

// List returns a filtered, paginated page of users.
func (s *Service) List(ctx context.Context, filter ListFilter, page pagination.OffsetPage) ([]*User, int64, error) {
	return s.repo.List(ctx, filter, page)
}
