// Package newcmd implements the portsmith new command.
package newcmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Run executes the new command to scaffold a new package.
func Run(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: portsmith new <pkg-dir>")
	}
	dir := args[0]
	base := filepath.Base(dir)
	name := toPascalCase(base)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}

	pkgName := strings.ToLower(base)
	data := templateData{
		Package: pkgName,
		Name:    name,
		Dir:     dir,
	}

	files := []struct {
		name    string
		content string
	}{
		{"domain.go", domainTpl},
		{"errors.go", errorsTpl},
		{"ports.go", portsTpl},
		{"service.go", serviceTpl},
		{"repository.go", repoTpl},
		{"handler.go", handlerTpl},
		{"dto.go", dtoTpl},
	}

	for _, f := range files {
		path := filepath.Join(dir, f.name)
		if _, err := os.Stat(path); err == nil {
			fmt.Printf("  skip  %s (already exists)\n", path)
			continue
		}
		if err := writeTemplate(path, f.content, data); err != nil {
			return fmt.Errorf("write %s: %w", f.name, err)
		}
		fmt.Printf("  create %s\n", path)
	}

	fmt.Printf("\nPackage scaffolded. Next steps:\n")
	fmt.Printf("  1. Add your domain fields to %s/domain.go\n", dir)
	fmt.Printf("  2. Implement service methods in %s/service.go\n", dir)
	fmt.Printf("  3. Run: portsmith gen %s\n", dir)
	fmt.Printf("  4. Run: portsmith mock %s\n", dir)
	return nil
}

type templateData struct {
	Package string
	Name    string
	Dir     string
}

func writeTemplate(path, tplContent string, data templateData) error {
	tpl, err := template.New("").Parse(tplContent)
	if err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, data)
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// --- Templates ---

const domainTpl = `package {{.Package}}

import "time"

// {{.Name}} is the primary domain entity for this package.
// Add your business fields here.
type {{.Name}} struct {
	ID        uint      ` + "`gorm:\"primaryKey\"`" + `
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Create{{.Name}}Params holds input data for creating a {{.Name}}.
type Create{{.Name}}Params struct {
	// TODO: add fields
}
`

const errorsTpl = `package {{.Package}}

import "github.com/miilkaa/portsmith/pkg/apperrors"

var (
	Err{{.Name}}NotFound = apperrors.NotFound("{{.Package}} not found")
)
`

const portsTpl = `package {{.Package}}

// ports.go is generated by: portsmith gen {{.Dir}}
// Run the command after implementing your service and repository methods.

import "context"

// {{.Name}}Repository is the storage port used by {{.Name}}Service.
type {{.Name}}Repository interface {
	// TODO: portsmith gen will populate this
	FindByID(ctx context.Context, id uint) (*{{.Name}}, error)
}

// {{.Name}}Service is the business logic port used by {{.Name}}Handler.
type {{.Name}}Service interface {
	// TODO: portsmith gen will populate this
	GetByID(ctx context.Context, id uint) (*{{.Name}}, error)
}

var (
	_ {{.Name}}Repository = (*Repository)(nil)
	_ {{.Name}}Service    = (*Service)(nil)
)
`

const serviceTpl = `package {{.Package}}

import "context"

// Service implements {{.Name}}Service.
type Service struct {
	repo {{.Name}}Repository
}

// NewService creates a new Service.
func NewService(repo {{.Name}}Repository) *Service {
	return &Service{repo: repo}
}

// GetByID returns a {{.Name}} by ID.
func (s *Service) GetByID(ctx context.Context, id uint) (*{{.Name}}, error) {
	return s.repo.FindByID(ctx, id)
}
`

const repoTpl = `package {{.Package}}

import (
	"context"
	"errors"

	"github.com/miilkaa/portsmith/pkg/database"
	"gorm.io/gorm"
)

// Repository implements {{.Name}}Repository using GORM.
type Repository struct {
	base database.Repository[{{.Name}}]
	db   *gorm.DB
}

// NewRepository creates a new Repository.
func NewRepository(db *gorm.DB) *Repository {
	return &Repository{base: database.NewRepository[{{.Name}}](db), db: db}
}

// FindByID retrieves a {{.Name}} by primary key.
func (r *Repository) FindByID(ctx context.Context, id uint) (*{{.Name}}, error) {
	entity, err := r.base.FindByID(ctx, id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, Err{{.Name}}NotFound
		}
		return nil, err
	}
	return entity, nil
}
`

const handlerTpl = `package {{.Package}}

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/miilkaa/portsmith/pkg/server"
)

// Handler handles HTTP requests for {{.Name}}.
type Handler struct {
	service {{.Name}}Service
}

// NewHandler creates a new Handler.
func NewHandler(service {{.Name}}Service) *Handler {
	return &Handler{service: service}
}

// Routes registers routes on the given router group.
func (h *Handler) Routes(rg *gin.RouterGroup) {
	g := rg.Group("/{{.Package}}")
	{
		g.GET("/:id", h.getByID)
	}
}

func (h *Handler) getByID(c *gin.Context) {
	// TODO: parse id, call service
	_ = server.BindAndValidate
	c.Status(http.StatusNotImplemented)
}
`

const dtoTpl = `package {{.Package}}

// {{.Name}}Response is the API representation of {{.Name}}.
type {{.Name}}Response struct {
	ID uint ` + "`json:\"id\"`" + `
	// TODO: add fields
}
`
