// Package newcmd implements the portsmith new command.
package newcmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/miilkaa/portsmith/internal/stack"
)

// Run executes the new command to scaffold a new package.
func Run(args []string) error {
	positional, stackFlag, err := parseArgs(args)
	if err != nil {
		return err
	}
	if len(positional) == 0 {
		return fmt.Errorf("usage: portsmith new [--stack gin-gorm|chi-sqlx] <pkg-dir>")
	}
	dir := positional[0]
	base := filepath.Base(dir)
	name := toPascalCase(base)

	pkgDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("abs path: %w", err)
	}
	st, err := stack.Resolve(pkgDir, stackFlag)
	if err != nil {
		return err
	}
	fmt.Printf("  stack: %s\n", st)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}

	pkgName := strings.ToLower(base)
	data := templateData{
		Package: pkgName,
		Name:    name,
		Dir:     dir,
	}

	tpls := templatesFor(st)
	files := []struct {
		name    string
		content string
	}{
		{"domain.go", tpls.domain},
		{"errors.go", errorsTpl},
		{"ports.go", tpls.ports},
		{"service.go", tpls.service},
		{"repository.go", tpls.repo},
		{"handler.go", tpls.handler},
		{"dto.go", tpls.dto},
	}

	for _, f := range files {
		path := filepath.Join(dir, f.name)
		if _, err := os.Stat(path); err == nil {
			fmt.Printf("  skip  %s (already exists)\n", path)
			continue
		}
		if err := writeTemplate(path, f.content, data); err != nil {
			return fmt.Errorf("write %s: %w", f.name, err)
		}
		fmt.Printf("  create %s\n", path)
	}

	fmt.Printf("\nPackage scaffolded. Next steps:\n")
	fmt.Printf("  1. Add your domain fields to %s/domain.go\n", dir)
	fmt.Printf("  2. Implement service methods in %s/service.go\n", dir)
	fmt.Printf("  3. Run: portsmith gen %s\n", dir)
	fmt.Printf("  4. Run: portsmith mock %s\n", dir)
	return nil
}

func parseArgs(args []string) (positional []string, stackFlag string, err error) {
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--stack":
			if i+1 >= len(args) {
				return nil, "", fmt.Errorf("--stack requires a value (gin-gorm or chi-sqlx)")
			}
			stackFlag = args[i+1]
			i++
		default:
			positional = append(positional, a)
		}
	}
	return positional, stackFlag, nil
}

type templateData struct {
	Package string
	Name    string
	Dir     string
}

type stackTemplates struct {
	domain, ports, service, repo, handler, dto string
}

func templatesFor(st stack.Stack) stackTemplates {
	switch st {
	case stack.ChiSqlx:
		return stackTemplates{
			domain:  domainTplChi,
			ports:   portsTplChi,
			service: serviceTplChi,
			repo:    repoTplChi,
			handler: handlerTplChi,
			dto:     dtoTplChi,
		}
	default:
		return stackTemplates{
			domain:  domainTplGin,
			ports:   portsTplGin,
			service: serviceTplGin,
			repo:    repoTplGin,
			handler: handlerTplGin,
			dto:     dtoTplGin,
		}
	}
}

func writeTemplate(path, tplContent string, data templateData) error {
	tpl, err := template.New("").Parse(tplContent)
	if err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, data)
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// --- Shared templates (errors identical for all stacks) ---

const errorsTpl = `package {{.Package}}

import "github.com/miilkaa/portsmith/pkg/apperrors"

var (
	Err{{.Name}}NotFound = apperrors.NotFound("{{.Package}} not found")
)
`

// --- Gin + GORM ---

const domainTplGin = `package {{.Package}}

import "time"

// {{.Name}} is the primary domain entity for this package.
// Add your business fields here.
type {{.Name}} struct {
	ID        uint      ` + "`gorm:\"primaryKey\"`" + `
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Create{{.Name}}Params holds input data for creating a {{.Name}}.
type Create{{.Name}}Params struct {
	// TODO: add fields
}
`

const portsTplGin = `package {{.Package}}

// ports.go is generated by: portsmith gen {{.Dir}}
// Run the command after implementing your service and repository methods.

import "context"

// {{.Name}}Repository is the storage port used by {{.Name}}Service.
type {{.Name}}Repository interface {
	// TODO: portsmith gen will populate this
	FindByID(ctx context.Context, id uint) (*{{.Name}}, error)
}

// {{.Name}}Service is the business logic port used by {{.Name}}Handler.
type {{.Name}}Service interface {
	// TODO: portsmith gen will populate this
	GetByID(ctx context.Context, id uint) (*{{.Name}}, error)
}

var (
	_ {{.Name}}Repository = (*Repository)(nil)
	_ {{.Name}}Service    = (*Service)(nil)
)
`

const serviceTplGin = `package {{.Package}}

import "context"

// Service implements {{.Name}}Service.
type Service struct {
	repo {{.Name}}Repository
}

// NewService creates a new Service.
func NewService(repo {{.Name}}Repository) *Service {
	return &Service{repo: repo}
}

// GetByID returns a {{.Name}} by ID.
func (s *Service) GetByID(ctx context.Context, id uint) (*{{.Name}}, error) {
	return s.repo.FindByID(ctx, id)
}
`

const repoTplGin = `package {{.Package}}

import (
	"context"
	"errors"

	"github.com/miilkaa/portsmith/pkg/database"
	"gorm.io/gorm"
)

// Repository implements {{.Name}}Repository using GORM.
type Repository struct {
	base database.Repository[{{.Name}}]
	db   *gorm.DB
}

// NewRepository creates a new Repository.
func NewRepository(db *gorm.DB) *Repository {
	return &Repository{base: database.NewRepository[{{.Name}}](db), db: db}
}

// FindByID retrieves a {{.Name}} by primary key.
func (r *Repository) FindByID(ctx context.Context, id uint) (*{{.Name}}, error) {
	entity, err := r.base.FindByID(ctx, id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, Err{{.Name}}NotFound
		}
		return nil, err
	}
	return entity, nil
}
`

const handlerTplGin = `package {{.Package}}

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/miilkaa/portsmith/pkg/server"
)

// Handler handles HTTP requests for {{.Name}}.
type Handler struct {
	service {{.Name}}Service
}

// NewHandler creates a new Handler.
func NewHandler(service {{.Name}}Service) *Handler {
	return &Handler{service: service}
}

// Routes registers routes on the given router group.
func (h *Handler) Routes(rg *gin.RouterGroup) {
	g := rg.Group("/{{.Package}}")
	{
		g.GET("/:id", h.getByID)
	}
}

func (h *Handler) getByID(c *gin.Context) {
	// TODO: parse id, call service
	_ = server.BindAndValidate
	c.Status(http.StatusNotImplemented)
}
`

const dtoTplGin = `package {{.Package}}

// {{.Name}}Response is the API representation of {{.Name}}.
type {{.Name}}Response struct {
	ID uint ` + "`json:\"id\"`" + `
	// TODO: add fields
}
`

// --- Chi + sqlx ---

const domainTplChi = `package {{.Package}}

import (
	"time"

	"github.com/google/uuid"
)

// {{.Name}} is the primary domain entity for this package.
// Add your business fields here.
type {{.Name}} struct {
	ID        uuid.UUID ` + "`db:\"id\"`" + `
	CreatedAt time.Time ` + "`db:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`db:\"updated_at\"`" + `
}

// Create{{.Name}}Params holds input data for creating a {{.Name}}.
type Create{{.Name}}Params struct {
	// TODO: add fields
}
`

const portsTplChi = `package {{.Package}}

// ports.go is generated by: portsmith gen {{.Dir}}
// Run the command after implementing your service and repository methods.

import (
	"context"

	"github.com/google/uuid"
)

// {{.Name}}Repository is the storage port used by {{.Name}}Service.
type {{.Name}}Repository interface {
	// TODO: portsmith gen will populate this
	FindByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
}

// {{.Name}}Service is the business logic port used by {{.Name}}Handler.
type {{.Name}}Service interface {
	// TODO: portsmith gen will populate this
	GetByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
}

var (
	_ {{.Name}}Repository = (*Repository)(nil)
	_ {{.Name}}Service    = (*Service)(nil)
)
`

const serviceTplChi = `package {{.Package}}

import (
	"context"

	"github.com/google/uuid"
)

// Service implements {{.Name}}Service.
type Service struct {
	repo {{.Name}}Repository
}

// NewService creates a new Service.
func NewService(repo {{.Name}}Repository) *Service {
	return &Service{repo: repo}
}

// GetByID returns a {{.Name}} by ID.
func (s *Service) GetByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error) {
	return s.repo.FindByID(ctx, id)
}
`

const repoTplChi = `package {{.Package}}

import (
	"context"
	"database/sql"
	"errors"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
)

// Repository implements {{.Name}}Repository using sqlx.
type Repository struct {
	db *sqlx.DB
}

// NewRepository creates a new Repository.
func NewRepository(db *sqlx.DB) *Repository {
	return &Repository{db: db}
}

// FindByID retrieves a {{.Name}} by primary key.
func (r *Repository) FindByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error) {
	const q = ` + "`SELECT id, created_at, updated_at FROM {{.Package}} WHERE id = $1`" + `
	var e {{.Name}}
	if err := r.db.GetContext(ctx, &e, q, id); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, Err{{.Name}}NotFound
		}
		return nil, err
	}
	return &e, nil
}
`

const handlerTplChi = `package {{.Package}}

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Handler handles HTTP requests for {{.Name}}.
type Handler struct {
	service {{.Name}}Service
}

// NewHandler creates a new Handler.
func NewHandler(service {{.Name}}Service) *Handler {
	return &Handler{service: service}
}

// Routes registers routes on a Chi router (mount under your API prefix).
func (h *Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Get("/{id}", h.getByID)
	return r
}

func (h *Handler) getByID(w http.ResponseWriter, r *http.Request) {
	// TODO: parse id (uuid), call service, write response
	_ = r
	w.WriteHeader(http.StatusNotImplemented)
}
`

const dtoTplChi = `package {{.Package}}

import "github.com/google/uuid"

// {{.Name}}Response is the API representation of {{.Name}}.
type {{.Name}}Response struct {
	ID uuid.UUID ` + "`json:\"id\"`" + `
	// TODO: add fields
}
`