package scaffold

// --- Shared templates (errors identical for all stacks) ---

const errorsTpl = `package {{.Package}}

import "errors"

var (
	Err{{.Name}}NotFound = errors.New("{{.Package}} not found")
)
`

// --- Gin + GORM ---

const domainTplGin = `package {{.Package}}

import "time"

// {{.Name}} is the primary domain entity for this package.
// Add your business fields here.
type {{.Name}} struct {
	ID        uint      ` + "`gorm:\"primaryKey\"`" + `
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Create{{.Name}}Params holds input data for creating a {{.Name}}.
type Create{{.Name}}Params struct {
	// TODO: add fields
}
`

const portsTplGin = `package {{.Package}}

// ports.go is generated by: portsmith gen {{.Dir}}
// Run the command after implementing your service and repository methods.

import "context"

// {{.Name}}Repository is the storage port used by {{.Name}}Service.
type {{.Name}}Repository interface {
	// TODO: portsmith gen will populate this
	FindByID(ctx context.Context, id uint) (*{{.Name}}, error)
}

// {{.Name}}Service is the business logic port used by {{.Name}}Handler.
type {{.Name}}Service interface {
	// TODO: portsmith gen will populate this
	GetByID(ctx context.Context, id uint) (*{{.Name}}, error)
}

var (
	_ {{.Name}}Repository = (*Repository)(nil)
	_ {{.Name}}Service    = (*Service)(nil)
)
`

const serviceTplGin = `package {{.Package}}

import "context"

// Service implements {{.Name}}Service.
type Service struct {
	repo {{.Name}}Repository
}

// NewService creates a new Service.
func NewService(repo {{.Name}}Repository) *Service {
	return &Service{repo: repo}
}

// GetByID returns a {{.Name}} by ID.
func (s *Service) GetByID(ctx context.Context, id uint) (*{{.Name}}, error) {
	return s.repo.FindByID(ctx, id)
}
`

const repoTplGin = `package {{.Package}}

import (
	"context"
	"errors"

	"gorm.io/gorm"
)

// Repository implements {{.Name}}Repository using GORM.
type Repository struct {
	db *gorm.DB
}

// NewRepository creates a new Repository.
func NewRepository(db *gorm.DB) *Repository {
	return &Repository{db: db}
}

// FindByID retrieves a {{.Name}} by primary key.
func (r *Repository) FindByID(ctx context.Context, id uint) (*{{.Name}}, error) {
	var entity {{.Name}}
	if err := r.db.WithContext(ctx).First(&entity, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, Err{{.Name}}NotFound
		}
		return nil, err
	}
	return &entity, nil
}
`

const handlerTplGin = `package {{.Package}}

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Handler handles HTTP requests for {{.Name}}.
type Handler struct {
	service {{.Name}}Service
}

// NewHandler creates a new Handler.
func NewHandler(service {{.Name}}Service) *Handler {
	return &Handler{service: service}
}

// Routes registers routes on the given router group.
func (h *Handler) Routes(rg *gin.RouterGroup) {
	g := rg.Group("/{{.Package}}")
	{
		g.GET("/:id", h.getByID)
	}
}

func (h *Handler) getByID(c *gin.Context) {
	// TODO: parse id, call service
	c.Status(http.StatusNotImplemented)
}
`

const dtoTplGin = `package {{.Package}}

// {{.Name}}Response is the API representation of {{.Name}}.
type {{.Name}}Response struct {
	ID uint ` + "`json:\"id\"`" + `
	// TODO: add fields
}
`

// --- Chi + sqlx ---

const domainTplChi = `package {{.Package}}

import (
	"time"

	"github.com/google/uuid"
)

// {{.Name}} is the primary domain entity for this package.
// Add your business fields here.
type {{.Name}} struct {
	ID        uuid.UUID ` + "`db:\"id\"`" + `
	CreatedAt time.Time ` + "`db:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`db:\"updated_at\"`" + `
}

// Create{{.Name}}Params holds input data for creating a {{.Name}}.
type Create{{.Name}}Params struct {
	// TODO: add fields
}
`

const portsTplChi = `package {{.Package}}

// ports.go is generated by: portsmith gen {{.Dir}}
// Run the command after implementing your service and repository methods.

import (
	"context"

	"github.com/google/uuid"
)

// {{.Name}}Repository is the storage port used by {{.Name}}Service.
type {{.Name}}Repository interface {
	// TODO: portsmith gen will populate this
	FindByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
}

// {{.Name}}Service is the business logic port used by {{.Name}}Handler.
type {{.Name}}Service interface {
	// TODO: portsmith gen will populate this
	GetByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error)
}

var (
	_ {{.Name}}Repository = (*Repository)(nil)
	_ {{.Name}}Service    = (*Service)(nil)
)
`

const serviceTplChi = `package {{.Package}}

import (
	"context"

	"github.com/google/uuid"
)

// Service implements {{.Name}}Service.
type Service struct {
	repo {{.Name}}Repository
}

// NewService creates a new Service.
func NewService(repo {{.Name}}Repository) *Service {
	return &Service{repo: repo}
}

// GetByID returns a {{.Name}} by ID.
func (s *Service) GetByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error) {
	return s.repo.FindByID(ctx, id)
}
`

const repoTplChi = `package {{.Package}}

import (
	"context"
	"database/sql"
	"errors"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
)

// Repository implements {{.Name}}Repository using sqlx.
type Repository struct {
	db *sqlx.DB
}

// NewRepository creates a new Repository.
func NewRepository(db *sqlx.DB) *Repository {
	return &Repository{db: db}
}

// FindByID retrieves a {{.Name}} by primary key.
func (r *Repository) FindByID(ctx context.Context, id uuid.UUID) (*{{.Name}}, error) {
	const q = ` + "`SELECT id, created_at, updated_at FROM {{.Package}} WHERE id = $1`" + `
	var e {{.Name}}
	if err := r.db.GetContext(ctx, &e, q, id); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, Err{{.Name}}NotFound
		}
		return nil, err
	}
	return &e, nil
}
`

const handlerTplChi = `package {{.Package}}

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Handler handles HTTP requests for {{.Name}}.
type Handler struct {
	service {{.Name}}Service
}

// NewHandler creates a new Handler.
func NewHandler(service {{.Name}}Service) *Handler {
	return &Handler{service: service}
}

// Routes registers routes on a Chi router (mount under your API prefix).
func (h *Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Get("/{id}", h.getByID)
	return r
}

func (h *Handler) getByID(w http.ResponseWriter, r *http.Request) {
	// TODO: parse id (uuid), call service, write response
	_ = r
	w.WriteHeader(http.StatusNotImplemented)
}
`

const dtoTplChi = `package {{.Package}}

import "github.com/google/uuid"

// {{.Name}}Response is the API representation of {{.Name}}.
type {{.Name}}Response struct {
	ID uuid.UUID ` + "`json:\"id\"`" + `
	// TODO: add fields
}
`
